### ISSUE TITLE
Assignment 7 (Beetles)

### ISSUE THREAD

**Issue by sagehartly** [sagehartly/dsn1674-assignment-7#1]
@thomasjbradley Just wanted to check something before I went ahead with the rest of the project - are the 4 images behind the green buttons meant to be background images? Or are we supposed to use position absolute/relative to put the green buttons on top? I know the dirt picture is supposed to be a background image, just not sure about the 4 bug pictures since they seem important to the function of the site.

Also, I've read through all the github articles for this week and can't find anything on how to make the brown bar in the header semi-transparent. Could you direct me to where that is? Is it supposed to be a gradient? Or just set at 50% transparency?

Thank you!
- Sage Mosurinjohn

**Comment by thomasjbradley** [comment]
I think you've answered your own question:

> Just not sure about the 4 bug pictures since they seem important to the function of the site.

Since they're an important part of the website they should be `<img>` tags with `position: relative` and `absolute`.

---

For the colours you'll want semi-transparent ones:
https://github.com/algonquindesign/html-css/tree/gh-pages/using-css#rgb-semi-transparency

**Comment by sagehartly** [comment]
@thomasjbradley Ok, thanks for your help! That makes sense. 

Sorry to have to bug you again but I'm having another separate issue now. When I drag the website folder into chrome it works fine but when I test the github url, none of the images work. I've attached a screen cap of how my image folder is set up. It seems to me like everything is in the right place but I must be missing something.

Thank you!
- Sage Mosurinjohn 

![screen shot 2015-04-05 at 8 44 06 pm](https://cloud.githubusercontent.com/assets/10467637/6999346/c1a36a94-dbd4-11e4-90ce-c1d07f0e1c43.png)
![screen shot 2015-04-05 at 8 43 46 pm](https://cloud.githubusercontent.com/assets/10467637/6999347/c9b5323a-dbd4-11e4-9b9f-7a9c771a939d.png)

**Comment by thomasjbradley** [comment]
Do all the files and folders follow our naming conventions?

**Comment by sagehartly** [comment]
Oh, I see that I have a capital "I" on my images folder and a couple of the file names. Would that cause this? I fixed it so that everything is in lower case in my files and folders and I did a commit and sync but nothing has changed. Is there anything else I should try?

**Comment by thomasjbradley** [comment]
That's definitely the cause, and even though you fixed it locally, did you notice that GitHub didn't recognize the change?

![screen shot 2015-04-05 at 9 36 23 pm](https://cloud.githubusercontent.com/assets/105192/6999541/de4b1cf8-dbdb-11e4-9aa1-0255df7d23b2.png)

That's because Mac OS X isn't case sensitive, as far as it's concerned nothing changed—but GitHub is case sensitive.
- You need to change the folder to something radical, like “----images”
- Commit and sync
- Then change it back to what you want and commit and sync again

**Comment by sagehartly** [comment]
Oh, that makes sense now! I was wondering why the commit and sync didn't change that list.

It all works now - thanks again for your help! 
- Sage
